name: Caching Primes

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: get boost
      run: |
        curl -s -OJL "https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz"
        tar zxvf boost_1_77_0.tar.gz
        ln -s boost_1_77_0 boost

    - name: Cache boost build
      id: boost
      uses: actions/cache@v3
      with:
        path: boost
        key: ${{ runner.os }}-primes

    - name: build boost
      if: steps.boost.outputs.cache-hit != 'true'
      run: |
        cd boost
        ./bootstrap
        ./b2

    - name: check boost
      run: ls -lah boost
