name: Build Clio

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-12]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: get boost
      run: |
        curl -s -OJL "https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz"
        tar zxf boost_1_77_0.tar.gz
        ln -s boost_1_77_0 boost

    - name: Cache boost build
      id: boost
      uses: actions/cache@v3
      with:
        path: boost
        key: ${{ runner.os }}-boost

    - name: build boost
      if: steps.boost.outputs.cache-hit != 'true'
      run: |
        ls -l
        cd boost
        ls -lah
        realpath .
        ./bootstrap.sh
        ./b2

    - name: check boost
      run: ls -lah boost

    - name: install deps
      run: |
        if [[ ${{ matrix.os }} =~ mac ]];then
            brew install pkg-config protobuf openssl ninja
        elif [[ ${{matrix.os }} =~ ubuntu ]];then
            sudo apt-get -y install git pkg-config protobuf-compiler libprotobuf-dev libssl-dev wget build-essential doxygen
            sudo apt-get -y install git pkg-config protobuf-compiler libprotobuf-dev libssl-dev wget build-essential bison flex autoconf cmake clang-format
        fi

    - name: Build clio
      run: |
        ls -l
        ls -l boost
        export BOOST_ROOT=$(pwd)/boost/boost
        cd clio
        cmake -B build
        cmake --build build -j$(nproc)
